### ISSUE TITLE
Minor issues with port and rest version, etc.

### ISSUE THREAD

**Issue by groupwhere** [ejstacey/skill-subsonic-media#1]
1.  If a port is not defined or defined correctly, the url will pass ":" at the end of the hostname.
2. I am using airsonic, and the api version is capped below 1.16.0.  I modified the code to read 1.15.0 and it worked.
3. I was not sure how to setup vlc and changed the code to use mpg123, which worked.

I had started working on a different skill when kathy pointed me to your code.  With a few tweaks I was able to get it working with airsonic.  The attached patch merely adjusts the api version and adds a check for whether port was set.

[subsonic.diff.txt](https://github.com/ejstacey/skill-subsonic-media/files/1856318/subsonic.diff.txt)

**Comment by groupwhere** [comment]
Regarding vlc, i ran a couple of small test programs and at one point set the volume using player.audio_set_volume(100) and then it miraculously started playing audio.

**Comment by ejstacey** [comment]
This is great, thanks!  I modified the if statement a bit to pass some flack8 standards checking, but otherwise perfect.  I'm not sure why I set the API level to whatever was my current highest.. there's no reason.  The stuff I use has been around for a long time, I believe.

VLC is definitely needed for HTTPS streaming, but as you noticed, using mpg123 works fine for HTTP.  If you keep experiencing issues with VLC please let me know and I'll either chase that more, or I'll only use vlc for HTTPS (although the problem may still exist then...).

Thanks again!

**Comment by groupwhere** [comment]
Thanks!  For some reason, it is working after a couple of reboots.  Somehow my volume level was set to 0 the first time.
